### PR TITLE
EVSRESTAPI-518 fix fhir concept map provider

### PR DESCRIPTION
**Pull request by gaaliciA1990**
Renaming classes and method names resulted multiple class files to be changed. These changes are small, renaming method calls and class refs.

The primary changes to code logic for the FHIR implementation is found in the following classes: 

`ConceptMapProvideR5` - translate methods, buildFhirQueryString, findPossibleConceptMaps
`ConceptMapProvideR4` - translate methods, buildFhirQueryString, findPossibleConceptMaps
`MapsetController` - getMapsetMappingsByCode, buildQueryString
`FhirUtilityR5` - toR5 method for ConceptMap
`ElasticSearchServiceImpl` - findConceptMappings
`ConceptUtils` - Added a bunch of methods for creating a string query
`FhirR5Tests` - All tests separated, added additional tests for ConceptMap. 
`FhirR4Tests` - All tests separated, added additional tests for ConceptMap. 

- I've updated the translate methods in the ConceptMapProvider classes for R4 and R5 to create a string query and call the findConceptMappings. Removed the for loop that was comparing our passed params to the list of possible maps, because that wasn't being used anymore with the query string being used instead.

### CODE REVIEW

**Comment by gaaliciA1990** [comment]
This is not complete and all tests are not passing. Requesting help with a small review

**Comment by gaaliciA1990** [comment]
The following tests are failing on my machine, but this may be due to my data. Need a second opinion. 
`testMapsetsWithMapsCodeWithNonZeroMatches()`
`testMapsetsWithMapsCodeWithNonZeroMatchesTrimSpacing()`
`testMapsetsWithMapsCodeWithNonZeroMatchesAndFromRecordAndPageSize()`

**Comment by gaaliciA1990** [comment]
Rebasing with develop branch to bring in those changes to avoid conflicts

**Review by bcarlsenca — APPROVED** [review]
will test once all together

**Pull request merged**
