### PR TITLE
subsets/mapsets to separate controllers/test files

### PR DESCRIPTION
**Pull request by peter-va**
https://tracker.nci.nih.gov/browse/EVSRESTAPI-335: Refactor mapping/subset calls into a new controller

### CODE REVIEW

**Review by bcarlsenca — COMMENTED** [review]
Just remove the mapset calls from metadata now. we've never released it so we don't need to keep them here.

**Review by bcarlsenca — COMMENTED** [review]
Also, I think for the subset controller we want to make the URLs like the metadata or concept controller, so instead of:

/{terminology}/subset/{code}

do this

/subset/{terminology}/{code}

**Review by bcarlsenca — COMMENTED** [review]
The URLs for MapsetController look good.

**Comment by peter-va** [comment]
removed deprecated calls and reordered subset calls to match mapsets

**Review by bcarlsenca — APPROVED** [review]
merging

**Pull request merged**
